AWSTemplateFormatVersion: "2010-09-09"
Resources:
  # Enabled HTTP method for an API resource
  <ApiMethodName>:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: <ApiMethod>
      ResourceId:
        Ref: <ApiResourceName>
      RestApiId:
        Ref: ApiGatewayRestApi
      RequestParameters: {}
      AuthorizationType: <AuthorizationType>
      AuthorizerId: <AuthorizerId>
      Integration:
        # NOTE: Lambda execution endpoint is always called with POST
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${<ApiFunctionName>.Arn}/invocations"
      MethodResponses: []

  # Add this method to the deployment dependencies
  ApiGatewayDeployment<ApiDeploymentId>:
    DependsOn:
    - <ApiMethodName>
