AWSTemplateFormatVersion: "2010-09-09"

Resources:
  # Extend custom resource to allow performing user-related operations
  CustomResourcePolicy:
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Resource: '*'
            Action:
              # The full reference is available here:
              # https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_actionsconditions.html
              - cognito-idp:CreateUserPool
              - cognito-idp:DeleteUserPool
              - cognito-idp:UpdateUserPool
              - cognito-idp:DescribeUserPool
              - cognito-idp:CreateUserPoolDomain
              - cognito-idp:DeleteUserPoolDomain
              - cognito-idp:DescribeUserPoolDomain
              - cognito-idp:UpdateUserPoolClient
              - cognito-idp:DescribeUserPoolClient
              - cognito-idp:CreateIdentityProvider
              - cognito-idp:UpdateIdentityProvider
              - cognito-idp:DeleteIdentityProvider
              - kms:GenerateRandom

  # The user pool for the registry
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName:
        Ref: AWS::StackName
      UsernameAttributes:
      - email

  # We need to perform a separate update to the UserPool, so that we can
  # add the 'PreTokenGeneration' property to 'LambdaConfig', which
  # the normal UserPool does not support
  UserPoolLambdaConfig:
    Type: Custom::CognitoUserPool
    DependsOn:
    - CustomResourcePolicy
    - CustomResourceLogGroup
    Properties:
      ServiceToken:
        Fn::GetAtt: CustomResourceLambdaFunction.Arn
      Service: CognitoIdentityServiceProvider
      Parameters:
        UserPoolId:
          Ref: UserPool
        LambdaConfig:
          PreTokenGeneration:
            Fn::GetAtt: UserPoolPreTokenGenerationLambdaFunction.Arn
      Create:
        Action: updateUserPool
      Update:
        Action: updateUserPool

  # Group for administrator users
  AdminUserPoolGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: Administrators of the application
      GroupName: Administrators
      Precedence: 10
      UserPoolId:
        Ref: UserPool

  # The domain for the user pool in the AWS Cognito
  UserPoolDomain:
    Type: Custom::CognitoUserPoolDomain
    DependsOn:
    - CustomResourcePolicy
    - CustomResourceLogGroup
    Properties:
      ServiceToken:
        Fn::GetAtt: CustomResourceLambdaFunction.Arn
      Service: CognitoIdentityServiceProvider
      PhysicalResourceId:
        # User pool domains are physically identified by the domain name
        Ref: AWS::StackName
      Parameters:
        UserPoolId:
          Ref: UserPool
        Domain:
          Ref: AWS::StackName
      Create:
        Action: createUserPoolDomain
      Delete:
        Action: deleteUserPoolDomain
        IgnoreErrors: true

  # The client for the user pool
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName:
        Fn::Sub: ${AWS::StackName}-client
      GenerateSecret: true
      UserPoolId:
        Ref: UserPool

  # Settings for the user pool client that cannot be set natively in CloudFormation
  UserPoolClientSettings:
    Type: Custom::CognitoUserPoolClientSettings
    DependsOn:
    - CustomResourcePolicy
    - CustomResourceLogGroup
    Properties:
      ServiceToken:
        Fn::GetAtt: CustomResourceLambdaFunction.Arn
      Service: CognitoIdentityServiceProvider
      Create:
        Action: updateUserPoolClient
        Parameters:
          UserPoolId:
            Ref: UserPool
          ClientId:
            Ref: UserPoolClient
          AllowedOAuthFlows:
            - code
          AllowedOAuthScopes:
            - openid
          AllowedOAuthFlowsUserPoolClient: true
          CallbackURLs:
            - Fn::Sub: ${ServerRoot}/oauth2/signin
          LogoutURLs:
            - Fn::Sub: ${ServerRoot}/oauth2/signout

  # The client secret is not available natively via CloudFormation
  # We retrieve it with the custom resource
  UserPoolClientSecret:
    Type: Custom::CognitoClientSecret
    DependsOn:
    - CustomResourcePolicy
    - CustomResourceLogGroup
    Properties:
      ServiceToken:
        Fn::GetAtt: CustomResourceLambdaFunction.Arn
      Service: CognitoIdentityServiceProvider
      Create:
        Action: describeUserPoolClient
        Attributes: UserPoolClient
        Parameters:
          UserPoolId:
            Ref: UserPool
          ClientId:
            Ref: UserPoolClient

  # Generate random bytes for the user session AES encryption key
  # The generated value is available as base64 encoded string with
  # Fn::GetAtt: UserSessionEncryptionKey.Plaintext
  UserSessionEncryptionKey:
    Type: Custom::KMSRandomBytes
    DependsOn:
    - CustomResourcePolicy
    - CustomResourceLogGroup
    Properties:
      ServiceToken:
        Fn::GetAtt: CustomResourceLambdaFunction.Arn
      Service: KMS
      Create:
        Action: generateRandom
        Parameters:
          NumberOfBytes: 32  # = 256 bits

  # Generate a secret for encrypting user session cookies
  UserSessionEncryptionKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name:
        Fn::Sub: "${AWS::StackName}/sessions/encryption-key"
      Description:
        Fn::Sub: "User session symmetric AES encryption key for ${AWS::StackName} CloudFormation stack"
      SecretString:
        Fn::Join:
          - ''
          - - '{"kty": "oct", "alg": "A256GCM", "k": "'
            # Convert the base64 encoded binary to base64url encoding
            # Remove the padding ('=')
            - Fn::Select:
              - 0
              - Fn::Split:
                - '='
                # Replace '+' with '-'
                - Fn::Join:
                  - '-'
                  - Fn::Split:
                    - '+'
                    # Replace '/' with '_'
                    - Fn::Join:
                      - '_'
                      - Fn::Split:
                        - '/'
                        - Fn::GetAtt: UserSessionEncryptionKey.Plaintext
            - '"}'

  # Authorizer for our API to allow authentication with the user pools
  ApiGatewayUserPoolAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Type: COGNITO_USER_POOLS
      Name: UserPoolAuthorizer
      IdentitySource: method.request.header.Authorization
      IdentityValidationExpression:
        Fn::Sub: "^${UserPoolClientSecret.ClientId}$"
      RestApiId:
        Ref: ServerApiGatewayRestApi
      ProviderARNs:
        - Fn::GetAtt: UserPool.Arn

  # Make authentication and user configuration information available for the server-side
  # Lambda function as environment variables
  ServerLambdaFunction:
    Properties:
      Environment:
        Variables:
          USER_SESSION_ENCRYPTION_KEY_SECRET_ARN:
            Ref: UserSessionEncryptionKeySecret

  # Make the user pool client information available for server-side rendering Lambda function
  # as API Gateway stage variables
  ServerApiGatewayStage:
    Properties:
      Variables:
        UserPoolId:
          Ref: UserPool
        AuthSignInUri:
          Fn::Sub: "https://${AWS::StackName}.auth.${AWS::Region}.amazoncognito.com/oauth2/authorize"
        AuthSignOutUri:
          Fn::Sub: "https://${AWS::StackName}.auth.${AWS::Region}.amazoncognito.com/logout"
        AuthTokenUri:
          Fn::Sub: "https://${AWS::StackName}.auth.${AWS::Region}.amazoncognito.com/oauth2/token"
        AuthSignInRedirectUri:
          Fn::Sub: "${ServerRoot}/oauth2/signin"
        AuthSignOutRedirectUri:
          Fn::Sub: "${ServerRoot}/oauth2/signout"
        AuthClientId:
          Ref: UserPoolClient
        AuthClientSecret:
          Fn::GetAtt: UserPoolClientSecret.ClientSecret

  # A lambda function that adds the 'picture' claim to the ID tokens on authentication
  UserPoolPreTokenGenerationLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role:
        Fn::GetAtt: LambdaExecutionIamRole.Arn
      Code:
        ZipFile: |
          exports.handler = (event, context, callback) => {
            let picture = event.request.userAttributes.picture;
            try {
                picture = JSON.parse(picture).data.url;
            } catch (err) {}
            if (typeof picture !== 'string' || !/^https?:\/\//.test(picture)) {
                picture = null;
            }
            event.response = {
              "claimsOverrideDetails": {
                "claimsToAddOrOverride": {
                  "picture": picture,
                }
              }
            };
            callback(null, event);
          };
      Runtime: nodejs8.10
      Timeout: 3

  # Grant the permission for the AWS Cognito to execute the Lambda trigger function
  UserPoolPreTokenGenerationLambdaFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt: UserPoolPreTokenGenerationLambdaFunction.Arn
      Principal: cognito-idp.amazonaws.com
      SourceArn:
        Fn::GetAtt: UserPool.Arn

  # Extend LambdaExecutionIamRolePolicy to allow operating on user pools
  LambdaExecutionIamRolePolicy:
    Properties:
      PolicyDocument:
        Statement:
        # Allow access to the user pool
        - Effect: Allow
          Action:
          - cognito-idp:AdminDeleteUser
          - cognito-idp:AdminGetUser
          - cognito-idp:AdminUpdateUserAttributes
          - cognito-idp:DeleteUser
          - cognito-idp:GetUser
          - cognito-idp:ListUsers
          - cognito-idp:UpdateUserAttributes
          Resource:
          - Fn::GetAtt: UserPool.Arn
        # Allow access to the user session key secret
        - Effect: Allow
          Action:
          - secretsmanager:GetSecretValue
          Resource:
          - Ref: UserSessionEncryptionKeySecret

Outputs:
  UserPoolRoot:
    Description: "Root URL for the AWS Cognito user pool"
    Value:
      Fn::Sub: "https://${AWS::StackName}.auth.${AWS::Region}.amazoncognito.com"
  UserPoolClientId:
    Description: "ID of the user pool client"
    Value:
      Ref: UserPoolClient
  UserPoolClientSecret:
    Description: "Generated secret for the user pool client"
    Value:
      Fn::GetAtt: UserPoolClientSecret.ClientSecret
  DatabaseTableUsersURI:
    Value:
      Fn::GetAtt: UserPool.Arn
  UserSessionEncryptionKeySecretArn:
    Description: ARN of the Secrets Manager user session encryption key
    Value:
      Ref: UserSessionEncryptionKeySecret
