AWSTemplateFormatVersion: "2010-09-09"
Resources:
  # Lambda function
  <ServerFunctionName>:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: DeploymentManagementS3Bucket
        S3Key:
          Ref: ServerRequestLambdaFunctionS3Key
      FunctionName:
        Fn::Sub: "${AWS::StackName}-<apiFunctionName>"
      Handler: server.request
      MemorySize: 1024
      Role:
        Fn::GetAtt: LambdaExecutionIamRole.Arn
      Runtime: nodejs10.x
      Timeout: 300  # = 5 minutes
    DependsOn:
    - <ServerFunctionName>LogGroup
    - LambdaExecutionIamRole

  # Grant API Gateway REST API a permission to execute the Lambda function
  <ServerFunctionName>PermissionApiGateway:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Fn::GetAtt: <ServerFunctionName>.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Sub: "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ServerApiGatewayRestApi}/*/*"

  # CloudWatch log group for the lambda function
  <ServerFunctionName>LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: "/aws/lambda/${AWS::StackName}-<apiFunctionName>"

# Output the log group name
Outputs:
  <ServerFunctionName>LogGroupName:
    Description: "Log group name of <apiFunctionName>"
    Value:
      Ref: <ServerFunctionName>LogGroup
