AWSTemplateFormatVersion: "2010-09-09"
Resources:
  # Lambda function for handling HTTP requests
  ServerLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: DeploymentManagementS3Bucket
        S3Key:
          Ref: ServerRequestLambdaFunctionS3Key
      FunctionName:
        Fn::Sub: "${AWS::StackName}-server"
      Handler: server.request
      MemorySize: 1024
      Role:
        Fn::GetAtt: LambdaExecutionIamRole.Arn
      Runtime: nodejs10.x
      Timeout: 300  # = 5 minutes
    DependsOn:
    - ServerLambdaFunctionLogGroup
    - LambdaExecutionIamRole

  # Grant API Gateway REST API a permission to execute the Lambda function
  ServerLambdaFunctionPermissionApiGateway:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Fn::GetAtt: ServerLambdaFunction.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Sub: "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ServerApiGatewayRestApi}/*/*"

  # CloudWatch log group for the lambda function
  ServerLambdaFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: "/aws/lambda/${AWS::StackName}-server"

# Output the log group name
Outputs:
  ServerLambdaFunctionLogGroupName:
    Description: "Log group name of the HTTP server Lambda function logs"
    Value:
      Ref: ServerLambdaFunctionLogGroup
