AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  # ID of the Facebook app client
  FacebookClientId:
    Type: String
  # Client secret of the Facebook app secret
  FacebookClientSecret:
    Type: String

Resources:
  # Enable Facebook as an identity provider for users to sign in
  FacebookIdentityProvider:
    Type: Custom::CognitoIdentityProvider
    DependsOn:
    - CustomResourcePolicy
    - CustomResourceLogGroup
    Properties:
      ServiceToken:
        Fn::GetAtt: CustomResourceLambdaFunction.Arn
      Service: CognitoIdentityServiceProvider
      Create:
        Action: createIdentityProvider
        Parameters:
          UserPoolId:
            Ref: UserPool
          ProviderName: Facebook
          ProviderType: Facebook
          ProviderDetails:
            authorize_scopes: public_profile,email
            # NOTE: We need to escape the 'true' string like this
            attributes_url_add_attributes: "${true}"
            authorize_url: https://www.facebook.com/v2.9/dialog/oauth
            token_url: https://graph.facebook.com/v2.9/oauth/access_token
            attributes_url: https://graph.facebook.com/me?fields=
            token_request_method: GET
            client_id:
              Ref: FacebookClientId
            client_secret:
              Ref: FacebookClientSecret
          AttributeMapping:
            email: email
            name: name
            picture: picture
      Update:
        Action: updateIdentityProvider
        Parameters:
          UserPoolId:
            Ref: UserPool
          ProviderName: Facebook
          ProviderDetails:
            authorize_scopes: public_profile,email
            # NOTE: We need to escape the 'true' string like this
            attributes_url_add_attributes: "${true}"
            authorize_url: https://www.facebook.com/v2.9/dialog/oauth
            token_url: https://graph.facebook.com/v2.9/oauth/access_token
            attributes_url: https://graph.facebook.com/me?fields=
            token_request_method: GET
            client_id:
              Ref: FacebookClientId
            client_secret:
              Ref: FacebookClientSecret
          AttributeMapping:
            email: email
            name: name
      Delete:
        Action: deleteIdentityProvider
        Parameters:
          ProviderName: Facebook
          UserPoolId:
            Ref: UserPool

  # Group for Facebook users, matching the one that would be created automatically by AWS
  FacebookUserPoolGroup:
    Type: AWS::Cognito::UserPoolGroup
    # TODO: This is for migrating existing group into the stack and can be deleted afterwards!
    DeletionPolicy: Retain
    Properties:
      Description: Autogenerated group for users who sign in using Facebook
      GroupName:
        Fn::Sub: ${UserPool}_Facebook
      UserPoolId:
        Ref: UserPool

  # Settings for the user pool client that cannot be set natively in CloudFormation
  UserPoolClientSettings:
    DependsOn:
    - FacebookIdentityProvider
    Properties:
      Create:
        Parameters:
          SupportedIdentityProviders:
            - Facebook
