AWSTemplateFormatVersion: "2010-09-09"
Resources:
  # Lambda function
  <ApiFunctionName>LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: DeploymentManagementS3Bucket
        S3Key:
          Ref: ApiRequestLambdaFunctionS3Key
      FunctionName:
        Fn::Sub: "${AWS::StackName}-<apiFunctionName>"
      Handler: api.request
      MemorySize: 1024
      Role:
        Fn::GetAtt: ["LambdaExecutionIamRole", "Arn"]
      Runtime: nodejs6.10
      Timeout: 6
    DependsOn:
    - <ApiFunctionName>LogGroup
    - LambdaExecutionIamRole

  # CloudWatch log group for the lambda function
  <ApiFunctionName>LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: "/aws/lambda/${AWS::StackName}-<apiFunctionName>"
