AWSTemplateFormatVersion: "2010-09-09"
Resources:
  # Lambda function
  <ApiFunctionName>:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: DeploymentManagementS3Bucket
        S3Key:
          Ref: ApiRequestLambdaFunctionS3Key
      FunctionName:
        Fn::Sub: "${AWS::StackName}-<apiFunctionName>"
      Handler: api.request
      MemorySize: 1024
      Role:
        Fn::GetAtt: ["LambdaExecutionIamRole", "Arn"]
      Runtime: nodejs10.x
      Timeout: 6
    DependsOn:
    - <ApiFunctionName>LogGroup
    - LambdaExecutionIamRole

  # Grant API Gateway REST API a permission to execute the Lambda function
  <ApiFunctionName>PermissionApiGateway:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Fn::GetAtt: ["<ApiFunctionName>", "Arn"]
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Sub: "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayRestApi}/*/*"

  # CloudWatch log group for the lambda function
  <ApiFunctionName>LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: "/aws/lambda/${AWS::StackName}-<apiFunctionName>"

# Output the log group name
Outputs:
  <ApiFunctionName>LogGroupName:
    Description: "Log group name of <apiFunctionName>"
    Value:
      Ref: <ApiFunctionName>LogGroup
