AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  # ID of the Facebook app client
  FacebookClientId:
    Type: String
  # Client secret of the Facebook app secret
  FacebookClientSecret:
    Type: String
    NoEcho: true

Resources:
  # Sub-stack for the custom resources
  CustomResource:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        Fn::Sub: https://s3.amazonaws.com/${DeploymentManagementS3Bucket}/cloudformation-custom-resource.yml

  # Policy that allows custom resource Lambda function to alter AWS service resources
  CustomResourcePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: SES
      Roles:
        - Fn::GetAtt: CustomResource.Outputs.Role
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Resource: '*'
            Action:
              # Add all the actions required for any used custom resources
              # The full reference is available here:
              # https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_actionsconditions.html
              - cognito-idp:CreateUserPoolDomain
              - cognito-idp:DeleteUserPoolDomain
              - cognito-idp:DescribeUserPoolDomain
              - cognito-idp:UpdateUserPoolClient
              - cognito-idp:DescribeUserPoolClient
              - cognito-idp:CreateIdentityProvider
              - cognito-idp:UpdateIdentityProvider
              - cognito-idp:DeleteIdentityProvider

  # The user pool for the registry
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName:
        Ref: AWS::StackName
      UsernameAttributes:
      - email

  # Group for administrator users
  AdminUserPoolGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: Administrators of the application
      GroupName: Administrators
      Precedence: 10
      UserPoolId:
        Ref: UserPool

  # The domain for the user pool in the AWS Cognito
  UserPoolDomain:
    Type: Custom::CognitoUserPoolDomain
    DependsOn:
    - CustomResourcePolicy
    Properties:
      ServiceToken:
        Fn::GetAtt: CustomResource.Outputs.ServiceToken
      Service: CognitoIdentityServiceProvider
      PhysicalResourceId:
        # User pool domains are physically identified by the domain name
        Ref: AWS::StackName
      Parameters:
        UserPoolId:
          Ref: UserPool
        Domain:
          Ref: AWS::StackName
      Create:
        Action: createUserPoolDomain
      Delete:
        Action: deleteUserPoolDomain
        IgnoreErrors: true

  # The client for the user pool
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName:
        Fn::Sub: ${AWS::StackName}-client
      GenerateSecret: true
      UserPoolId:
        Ref: UserPool

  # Settings for the user pool client that cannot be set natively in CloudFormation
  UserPoolClientSettings:
    Type: Custom::CognitoUserPoolClientSettings
    DependsOn:
    - CustomResourcePolicy
    - FacebookIdentityProvider
    Properties:
      ServiceToken:
        Fn::GetAtt: CustomResource.Outputs.ServiceToken
      Service: CognitoIdentityServiceProvider
      Create:
        Action: updateUserPoolClient
        Parameters:
          UserPoolId:
            Ref: UserPool
          ClientId:
            Ref: UserPoolClient
          AllowedOAuthFlows:
            - code
            - implicit
          AllowedOAuthScopes:
            - openid
          SupportedIdentityProviders:
            - COGNITO
            - Facebook
          AllowedOAuthFlowsUserPoolClient: true
          CallbackURLs:
            - Fn::Sub: ${SiteRoot}/_oauth2_signin_complete.html
          LogoutURLs:
            - Fn::Sub: ${SiteRoot}/_oauth2_signout_complete.html

  # Enable Facebook as an identity provider for users to sign in
  FacebookIdentityProvider:
    Type: Custom::CognitoIdentityProvider
    DependsOn:
    - CustomResourcePolicy
    Properties:
      ServiceToken:
        Fn::GetAtt: CustomResource.Outputs.ServiceToken
      Service: CognitoIdentityServiceProvider
      Create:
        Action: createIdentityProvider
        Parameters:
          UserPoolId:
            Ref: UserPool
          ProviderName: Facebook
          ProviderType: Facebook
          ProviderDetails:
            authorize_scopes: public_profile,email
            # NOTE: We need to escape the 'true' string like this
            attributes_url_add_attributes: "${true}"
            authorize_url: https://www.facebook.com/v2.9/dialog/oauth
            token_url: https://graph.facebook.com/v2.9/oauth/access_token
            attributes_url: https://graph.facebook.com/me?fields=
            token_request_method: GET
            # TODO: From a parameter!
            client_id:
              Ref: FacebookClientId
            # TODO: From a parameter!
            client_secret:
              Ref: FacebookClientSecret
          AttributeMapping:
            email: email
            name: name
      Update:
        Action: updateIdentityProvider
        Parameters:
          UserPoolId:
            Ref: UserPool
          ProviderName: Facebook
          ProviderDetails:
            authorize_scopes: public_profile,email
            # NOTE: We need to escape the 'true' string like this
            attributes_url_add_attributes: "${true}"
            authorize_url: https://www.facebook.com/v2.9/dialog/oauth
            token_url: https://graph.facebook.com/v2.9/oauth/access_token
            attributes_url: https://graph.facebook.com/me?fields=
            token_request_method: GET
            # TODO: From a parameter!
            client_id:
              Ref: FacebookClientId
            # TODO: From a parameter!
            client_secret:
              Ref: FacebookClientSecret
          AttributeMapping:
            email: email
            name: name
      Delete:
        Action: deleteIdentityProvider
        Parameters:
          ProviderName: Facebook
          UserPoolId:
            Ref: UserPool

  # The client secret is not available natively via CloudFormation
  # We retrieve it with the custom resource
  UserPoolClientSecret:
    Type: Custom::CognitoClientSecret
    DependsOn:
    - CustomResourcePolicy
    Properties:
      ServiceToken:
        Fn::GetAtt: CustomResource.Outputs.ServiceToken
      Service: CognitoIdentityServiceProvider
      Create:
        Action: describeUserPoolClient
        Attributes: UserPoolClient
        Parameters:
          UserPoolId:
            Ref: UserPool
          ClientId:
            Ref: UserPoolClient

  # Authorizer for our API to allow authentication with the user pools
  ApiGatewayUserPoolAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Type: COGNITO_USER_POOLS
      Name: UserPoolAuthorizer
      IdentitySource: method.request.header.Authorization
      IdentityValidationExpression:
        Fn::Sub: "^${UserPoolClientSecret.ClientId}$"
      RestApiId:
        Ref: ApiGatewayRestApi
      ProviderARNs:
        - Fn::GetAtt: UserPool.Arn

  # Make the user pool ARN available for Lambda functions as a stage variable
  ApiGatewayStage:
    Properties:
      Variables:
        DatabaseTableUsersURI:
          Fn::GetAtt: UserPool.Arn

Outputs:
  UserPoolRoot:
    Description: "Root URL for the AWS Cognito user pool"
    Value:
      Fn::Sub: "https://${AWS::StackName}.auth.${AWS::Region}.amazoncognito.com"
  UserPoolClientId:
    Description: "ID of the user pool client"
    Value:
      Ref: UserPoolClient
  UserPoolClientSecret:
    Description: "Generated secret for the user pool client"
    Value:
      Fn::GetAtt: UserPoolClientSecret.ClientSecret
