AWSTemplateFormatVersion: "2010-09-09"
Resources:
  # Enabled HTTP method for an API resource
  <ServerMethodName>:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: <ServerMethod>
      ResourceId: <ServerResourceId>
      RestApiId:
        Ref: ServerApiGatewayRestApi
      RequestParameters: {}
      AuthorizationType: "NONE"
      Integration:
        # NOTE: Lambda execution endpoint is always called with POST
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ServerLambdaFunction.Arn}/invocations"
      MethodResponses: []

  # Add this method to the deployment dependencies
  ServerApiGatewayDeployment<ServerDeploymentId>:
    DependsOn:
    - <ServerMethodName>
